---
 - name: Install node_exporter to all hosts
   hosts: all
   gather_facts: no
   become: true
   tasks:
     - name: Make directory on the remote host
       file:
         path: /root/node_exporter
         owner: root
         group: root
         state: directory

     - name: Copy docker-compose.yml to remote directory
       copy:
         src: /etc/ansible/templates/node_exporter.yml
         dest: /root/node_exporter/docker-compose.yml

     - name: install pip
       package:
         name:
           - pip
      
     - name: install python dependenies
       pip:
         name:
           - docker
           - docker-compose

     - name: Deploy docker-compose file
       docker_compose:
         project_src: /root/node_exporter
         files:
         - docker-compose.yml
         recreate: smart
       register: check

     - name: check the status
       debug:
         var: check.services
