---
 - name: use gather_facts
   hosts: all
   gather_facts: yes
   tasks:
   - debug:
       msg:
        - "The os_dist is : {{ansible_distribution}}"
        - "The os name is: {{ansible_system}}"
        - "The os family is: {{ansible_os_family}}" 
