global:
  scrape_interval: 15s
  external_labels:
    monitor: 'first-monitor'

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:          #tartget IP
      - targets: ['127.0.0.1:9090']

  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node_exporter:9100']
      - targets: ['192.168.1.244:9100']

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']
      - targets: ['192.168.1.244:8080']
